### ISSUE TITLE
quasar-cli Error on Ubuntu ARM

### ISSUE THREAD

**Issue by searli** [quasarframework/quasar-cli#13]
Running Ubuntu ARM on Chromebook in chroot environment; 

installed npm (v2.15.9) and nodejs (v4.5.0) 

installed quasar through npm
> sudo npm install -g quasar-cli

when running **quasar init <project>** i get following error
```

 ℹ Generating Quasar App...

⠧ Determining newest template.../usr/local/lib/node_modules/quasar-cli/lib/template-list.js:18
      JSON.parse(branches).filter(function (branch) {
                           ^

TypeError: JSON.parse(...).filter is not a function
    at Request._callback (/usr/local/lib/node_modules/quasar-cli/lib/template-list.js:18:28)
    at Request.self.callback (/usr/local/lib/node_modules/quasar-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/quasar-cli/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/quasar-cli/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

   ╭───────────────────────────────────────╮
   │                                                                                                    │
   │    Update available 0.2.0 → 0.4.1                                               │
   │   Run npm i -g quasar-cli to update                                            │
   │                                                                                                    │
   ╰───────────────────────────────────────╯



```
Running npm i -g quasar-cli to update does not solve the problem;

**Comment by rstoenescu** [comment]
Hmm, please really install latest version (0.4.1).
