### ISSUE TITLE
quasar init -v <any version> returns error

### ISSUE THREAD

**Issue by marekkaczkowski** [quasarframework/quasar-cli#133]
### Software version

OS: macOS Sierra 10.12.6 (16G1408)
Node: v8.10.0
NPM: 6.1.0
vue-cli: 2.9.3
quasar-cli: 0.16.4

### What did you get as the error?

```
quasar init -v 0.15 quasar-testing-unit-jest
 Running command: vue init '#v0.15' quasar-testing-unit-jest

downloading template
/usr/local/lib/node_modules/vue-cli/node_modules/download-git-repo/index.js:59
  var type = match[2] || 'github'
                  ^

TypeError: Cannot read property '2' of null
    at normalize (/usr/local/lib/node_modules/vue-cli/node_modules/download-git-repo/index.js:59:19)
    at download (/usr/local/lib/node_modules/vue-cli/node_modules/download-git-repo/index.js:28:10)
    at downloadAndGenerate (/usr/local/lib/node_modules/vue-cli/bin/vue-init:150:3)
    at checkVersion (/usr/local/lib/node_modules/vue-cli/bin/vue-init:122:11)
    at Request.request [as _callback] (/usr/local/lib/node_modules/vue-cli/lib/check-version.js:29:5)
    at Request.self.callback (/usr/local/lib/node_modules/vue-cli/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/vue-cli/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/vue-cli/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
 app:init ⚠️ Something went wrong... Try running the "vue init" command above manually. +0ms
 app:init Reasons for failure: Package @vue/cli and @vue/cli-init are not installed globally, specified template is unavailable or it failed to download. +1ms
```

### What were you expecting?

Expected to init quasar project with version v0.15 (looks like `download-git-repo` can't find v0.15 tag in quasar repo).

### What steps did you take, to get the error?

Run `quasar init -v 0.15 quasar-testing-unit-jest`

**Comment by rstoenescu** [comment]
Fixed it. Thanks for reporting. Will be available in CLI v0.16.5
