### ISSUE TITLE
Error: Cannot find module 'ci-info' during quasar init

### ISSUE THREAD

**Issue by naknode** [quasarframework/quasar-cli#161]
### Software version

OS: Windows 10
Node: 8.11.1
NPM: 5.6.0
Any other software related to your bug:
Vue CLI: 2.9.6

### What did you get as the error?
```
$ quasar init testapp
module.js:549
    throw err;
    ^

Error: Cannot find module 'ci-info'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\dev1\node_modules\is-ci\index.js:3:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

### What were you expecting?
For the Quasar CLI to go through its getting-started process

### What steps did you take, to get the error?

```
npm install -g vue-cli
npm install -g quasar-cli
cd /code
quasar init testapp
```

I have tried restarting terminal, etc. I am using Git Bash. Also have tried regular command prompt. Yes, it's in my path. Yes I can do other global NPM packages.

**Comment by rstoenescu** [comment]
What CLI version are you using?? There's no `is-ci` package in the CLI....

**Comment by naknode** [comment]
I apologize @rstoenescu . I am using the latest. 0.17.6. 

and it is here: https://github.com/quasarframework/quasar-cli/blob/dev/package.json#L50
